### PR TITLE
Prevent deadlocking on the visit table

### PR DESCRIPTION
**Pull request by will-mooney-3**
Indents hub.commit. More transactions, same number of writes

@fuhrysteve @EricWorkman

### CODE REVIEW

**Comment by evanstern** [comment]
I can seeeeeee you :stuck_out_tongue_winking_eye:

**Comment by will-mooney-3** [comment]
EVAN!!!!!!!!!!!

Hi! :wave:

**Comment by ortizub41** [comment]
Hi Evan!

**Comment by fuhrysteve** [comment]
Looks reasonable to me. I can't think of anything this would screw up, and if it makes those locking transactions shorter then great.

**Pull request merged**
